# Fabric Properties
# Minecraft version
minecraft_version=1.21.6
# Fabric loader version
loader_version=0.18.1
# Fabric API version
fabric_version=0.128.1+1.21.6
# Loom version
loom_version=1.14.1

# Mod Properties
mod_version=1.1.0
maven_group=com.spyglasshud
archives_base_name=spyglass-only-hud

# Java version
java_version=21

# Modrinth
modrinth_project_id=CHANGE_ME
