# Fabric Properties
# Minecraft version
minecraft_version=26.1.2
# Fabric loader version
loader_version=0.18.5
# Fabric API version
fabric_version=0.145.4+26.1.2

# Mod Properties
mod_version=1.1.1
maven_group=com.spyglasshud
archives_base_name=spyglass-only-hud

# Java version
java_version=25

# Modrinth
modrinth_project_id=CHANGE_ME
