# Fabric Properties
# Minecraft version
minecraft_version=26.1-pre-2
# Yarn mappings version (adjust to match your snapshot)
yarn_mappings=26.1-pre-2+build.1
# Fabric loader version
loader_version=0.18.4
# Fabric API version
fabric_version=0.143.13+26.1

# Mod Properties
mod_version=1.0.2
maven_group=com.spyglasshud
archives_base_name=spyglass-only-hud

# Java version
java_version=25

# Modrinth
modrinth_project_id=CHANGE_ME
